backend:
    name: git-gateway
    branch: main # or "master" — match your repo's default branch

collections:
    - name: "posts" # Used in routes, e.g., /admin/collections/blog
      label: "Posts" # Used in the UI
      folder: "src/pages/posts" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      fields: # The fields for each document, usually in frontmatter
          - {
                label: "Layout",
                name: "layout",
                widget: "hidden",
                default: "../../layouts/MarkdownPostLayout.astro",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "pubDate", widget: "datetime" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Thumbnail", name: "thumbnail", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media
